name: container

on:
  push:
    branches:
      - main

jobs:
  analize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/auth
    steps: 
      - name: analize events
        uses: actions/checkout@v3
      - run: echo ${{github.event.head_commit.message.includes('fix')}}